name: CI/CD

on: push

env:
  AWS_DEFAULT_REGION: us-east-1
  PIPENV_NOSPIN: true
  PIPENV_VENV_IN_PROJECT: true
  PIPENV_YES: true

jobs:
  test-python:
    name: Python Linting & Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0.0
      - name: Install Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip Cache (ubuntu)
        uses: actions/cache@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ matrix.python-version }}
          restore-keys: |
            ${{ matrix.os }}-pip-${{ matrix.python-version }}
      - name: Install Global Python Packages
        run: |
          python -m pip install --upgrade pip setuptools
          pip install "virtualenv==16.7.9" "pipenv==2018.11.26"
      - name: Pipenv Cache
        uses: actions/cache@v1
        with:
          path: ./.venv
          key: ${{ github.ref	}}-${{ matrix.os }}-venv-${{ matrix.python-version }}
          restore-keys: |
            ${{ github.ref	}}-${{ matrix.os }}-venv-${{ matrix.python-version }}
      - name: Setup Python Virtual Environment
        run: pipenv sync --dev
      - name: Run Linters
        run: make lint
